export const TOP = 0, RIGHT = 1, BOTTOM = 2, LEFT = 3;

export const PROTECTOR = 1, ARCHER = 2, MELEE = 3;

export const 
POSITION = 1,
KEYBOARDCONTROL = 2,
BODY = 3,
ANIMATION = 4,
HEALTH = 5,
SPRITE = 6,
DAMAGE = 7,
FRIEND = 8,
PLAYER = 9,
KNOCKBACK = 10,
CAMERA = 11,
CIRCLESWEAPON = 12,
SPAWN = 13,
BTREE = 14,
TEXT = 15,
SELFDESTRUCT = 16,
ENEMY = 17,
INVULNERABLE = 18,
DUMB_AI = 19,
TWEEN = 20;
